In [1]:
import pandas as pd
from ucimlrepo import fetch_ucirepo

horse_colic = fetch_ucirepo(id=47)

X = horse_colic.data.features.copy()
y = horse_colic.data.targets.copy()

df = pd.concat([X, y], axis=1)

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace('-', '_', regex=False)
    .str.replace(' ', '_', regex=False)
)

target_column = y.columns[0]
target_column = target_column.strip().lower().replace('-', '_').replace(' ', '_')

df_reduced = pd.read_csv("horse_colic_reduced.csv")

print(df.shape)
print(df.head())

(368, 28)
   surgery  age  hospital_number  rectal_temperature  pulse  respiratory_rate  \
0      2.0    1           530101                38.5   66.0              28.0
1      1.0    1           534817                39.2   88.0              20.0
2      2.0    1           530334                38.3   40.0              24.0
3      1.0    9          5290409                39.1  164.0              84.0
4      2.0    1           530255                37.3  104.0              35.0

   temperature_of_extremities  peripheral_pulse  mucous_membranes  \
0                         3.0               3.0               NaN
1                         NaN               NaN               4.0
2                         1.0               1.0               3.0
3                         4.0               1.0               6.0
4                         NaN               NaN               6.0

   capillary_refill_time  ...  packed_cell_volume  total_protein  \
0                    2.0  ...                45.0            8.4
1                    1.0  ...                50.0           85.0
2                    1.0  ...                33.0            6.7
3                    2.0  ...                48.0            7.2
4                    2.0  ...                74.0            7.4

   abdominocentesis_appearance  abdominocentesis_total_protein  outcome  \
0                          NaN                             NaN      2.0
1                          2.0                             2.0      3.0
2                          NaN                             NaN      1.0
3                          3.0                             5.3      2.0
4                          NaN                             NaN      2.0

   lesion_site  lesion_type  lesion_subtype  cp_data  surgical_lesion
0        11300            0               0        2                2
1         2208            0               0        2                2
2            0            0               0        1                2
3         2208            0               0        1                1
4         4300            0               0        2                2

[5 rows x 28 columns]

In [2]:
categorical_columns = df.select_dtypes(include=['object']).columns
numeric_columns = df.select_dtypes(include=['number']).columns

print("Категориальные данные:", categorical_columns)
print("Числовые данные:", numeric_columns)
print("Целевая переменная:", target_column)
print("Размер датасета:", df.shape)
print("Пропуски по столбцам:")
print(df.isnull().sum())

Категориальные данные: Index([], dtype='object')
Числовые данные: Index(['surgery', 'age', 'hospital_number', 'rectal_temperature', 'pulse',
       'respiratory_rate', 'temperature_of_extremities', 'peripheral_pulse',
       'mucous_membranes', 'capillary_refill_time', 'pain', 'peristalsis',
       'abdominal_distension', 'nasogastric_tube', 'nasogastric_reflux',
       'nasogastric_reflux_ph', 'rectal_examination_feces', 'abdomen',
       'packed_cell_volume', 'total_protein', 'abdominocentesis_appearance',
       'abdominocentesis_total_protein', 'outcome', 'lesion_site',
       'lesion_type', 'lesion_subtype', 'cp_data', 'surgical_lesion'],
      dtype='object')
Целевая переменная: surgical_lesion
Размер датасета: (368, 28)
Пропуски по столбцам:
surgery                             2
age                                 0
hospital_number                     0
rectal_temperature                 69
pulse                              26
respiratory_rate                   71
temperature_of_extremities         65
peripheral_pulse                   83
mucous_membranes                   48
capillary_refill_time              38
pain                               63
peristalsis                        52
abdominal_distension               65
nasogastric_tube                  131
nasogastric_reflux                133
nasogastric_reflux_ph             299
rectal_examination_feces          128
abdomen                           143
packed_cell_volume                 37
total_protein                      43
abdominocentesis_appearance       194
abdominocentesis_total_protein    235
outcome                             2
lesion_site                         0
lesion_type                         0
lesion_subtype                      0
cp_data                             0
surgical_lesion                     0
dtype: int64

In [3]:
X = df.drop(target_column, axis=1)
y = df[target_column]

X_reduced = df_reduced.drop(target_column, axis=1)
y_reduced = df_reduced[target_column]

X_encoded = pd.get_dummies(X, dtype=int)
X_reduced_encoded = pd.get_dummies(X_reduced, dtype=int)

df_encoded = pd.concat(
    [X_encoded, y.rename(target_column)],
    axis=1
)

df_reduced_encoded = pd.concat(
    [X_reduced_encoded, y_reduced.rename(target_column)],
    axis=1
)

print(df_encoded.shape)
df_encoded.head()

(368, 28)

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdominocentesis_total_protein,outcome,lesion_site,lesion_type,lesion_subtype,cp_data,surgical_lesion
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,11300,0,0,2,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2208,0,0,2,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,0,0,0,1,2
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,2208,0,0,1,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,4300,0,0,2,2

In [4]:
df_encoded.describe()

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdominocentesis_total_protein,outcome,lesion_site,lesion_type,lesion_subtype,cp_data,surgical_lesion
count,366.000000,368.000000,3.680000e+02,299.000000,342.000000,297.000000,303.000000,285.000000,320.000000,330.000000,...,331.000000,325.000000,174.000000,133.000000,366.000000,368.000000,368.000000,368.000000,368.000000,368.000000
mean,1.415301,1.608696,1.112334e+06,38.134448,70.757310,30.521886,2.356436,1.961404,2.834375,1.303030,...,45.656798,24.771077,2.045977,2.948120,1.527322,3650.834239,96.972826,6.002717,1.663043,1.369565
std,0.493448,2.123985,1.560122e+06,0.711684,28.089867,17.669651,1.041371,1.052454,1.591732,0.473289,...,10.865663,27.704880,0.803289,1.927064,0.731347,5360.219154,640.506258,115.152085,0.473313,0.483344
min,1.000000,1.000000,5.142790e+05,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000,1.000000,...,4.000000,3.300000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,1.000000,1.000000,5.289152e+05,37.800000,48.000000,18.000000,1.000000,1.000000,1.000000,1.000000,...,37.250000,6.500000,1.000000,2.000000,1.000000,2111.750000,0.000000,0.000000,1.000000,1.000000
50%,1.000000,1.000000,5.302990e+05,38.100000,60.000000,28.000000,3.000000,1.000000,3.000000,1.000000,...,44.000000,7.500000,2.000000,2.100000,1.000000,3025.000000,0.000000,0.000000,2.000000,1.000000
75%,2.000000,1.000000,5.347275e+05,38.500000,88.000000,36.000000,3.000000,3.000000,4.000000,2.000000,...,52.000000,58.000000,3.000000,3.900000,2.000000,3209.000000,0.000000,0.000000,2.000000,2.000000
max,2.000000,9.000000,5.305629e+06,40.800000,184.000000,96.000000,4.000000,4.000000,6.000000,3.000000,...,75.000000,89.000000,3.000000,10.100000,3.000000,41110.000000,7111.000000,2209.000000,2.000000,2.000000

In [5]:
df_encoded.to_csv("horse_colic_normalized.csv", index=False)

df_reduced_encoded.to_csv(
    "horse_colic_reduced_encoded.csv",
    index=False
)

print(df_reduced_encoded.shape)
df_reduced_encoded.head()

(368, 15)

,surgery,hospital_number,rectal_temperature,pulse,respiratory_rate,mucous_membranes,pain,peristalsis,abdominal_distension,abdomen,packed_cell_volume,total_protein,outcome,lesion_site,surgical_lesion
0,2.0,530101,38.5,66.0,28.0,NaN,5.0,4.0,4.0,5.0,45.0,8.4,2.0,11300,2
1,1.0,534817,39.2,88.0,20.0,4.0,3.0,4.0,2.0,2.0,50.0,85.0,3.0,2208,2
2,2.0,530334,38.3,40.0,24.0,3.0,3.0,3.0,1.0,1.0,33.0,6.7,1.0,0,2
3,1.0,5290409,39.1,164.0,84.0,6.0,2.0,4.0,4.0,NaN,48.0,7.2,2.0,2208,1
4,2.0,530255,37.3,104.0,35.0,6.0,NaN,NaN,NaN,NaN,74.0,7.4,2.0,4300,2