In [1]:
import pandas as pd

df = pd.read_csv('/home/egor/machineLearing/lab7/tic_tac_toe_cleaned.csv', delimiter=',')
df_reduced = pd.read_csv(
    "/home/egor/machineLearing/lab7/tic_tac_toe_reduced.csv",
    delimiter=","
)

print(df.shape)

(958, 10)

In [2]:
categorical_columns = df.select_dtypes(include=['object']).columns
numeric_columns = df.select_dtypes(include=['number']).columns

target_column = 'class'

print("Категориальные данные:", categorical_columns)
print("Числовые данные:", numeric_columns)
print("Целевая переменная:", target_column)
print("Размер датасета:", df.shape)
print("Пропуски по столбцам:")
print(df.isnull().sum())

Категориальные данные: Index(['top_left_square', 'top_middle_square', 'top_right_square',
       'middle_left_square', 'middle_middle_square', 'middle_right_square',
       'bottom_left_square', 'bottom_middle_square', 'bottom_right_square',
       'class'],
      dtype='object')
Числовые данные: Index([], dtype='object')
Целевая переменная: class
Размер датасета: (958, 10)
Пропуски по столбцам:
top_left_square         0
top_middle_square       0
top_right_square        0
middle_left_square      0
middle_middle_square    0
middle_right_square     0
bottom_left_square      0
bottom_middle_square    0
bottom_right_square     0
class                   0
dtype: int64

In [3]:
X = df.drop('class', axis=1)
y = df['class'].map({
    'negative': 0,
    'positive': 1
})
X_reduced = df_reduced.drop("class", axis=1)

y_reduced = df_reduced["class"].map({
    "negative": 0,
    "positive": 1
})
X_encoded = pd.get_dummies(X, dtype=int)
X_reduced_encoded = pd.get_dummies(X_reduced, dtype=int)

df_reduced_encoded = pd.concat(
    [X_reduced_encoded, y_reduced.rename("class")],
    axis=1
)
df_encoded = pd.concat([X_encoded, y.rename('class')], axis=1)
df_encoded.head()
print(df_encoded.shape)

(958, 28)

In [4]:
df_encoded.describe()

,top_left_square_b,top_left_square_o,top_left_square_x,top_middle_square_b,top_middle_square_o,top_middle_square_x,top_right_square_b,top_right_square_o,top_right_square_x,middle_left_square_b,...,bottom_left_square_b,bottom_left_square_o,bottom_left_square_x,bottom_middle_square_b,bottom_middle_square_o,bottom_middle_square_x,bottom_right_square_b,bottom_right_square_o,bottom_right_square_x,class
count,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,...,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000
mean,0.213987,0.349687,0.436326,0.260960,0.344468,0.394572,0.213987,0.349687,0.436326,0.260960,...,0.213987,0.349687,0.436326,0.260960,0.344468,0.394572,0.213987,0.349687,0.436326,0.653445
std,0.410332,0.477120,0.496188,0.439388,0.475443,0.489014,0.410332,0.477120,0.496188,0.439388,...,0.410332,0.477120,0.496188,0.439388,0.475443,0.489014,0.410332,0.477120,0.496188,0.476121
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
csv_file_data = "/home/egor/machineLearing/lab7/tic_tac_normilize.csv"
df_encoded.to_csv(csv_file_data, index=False)
df_reduced_encoded.to_csv(
    "/home/egor/machineLearing/lab7/tic_tac_reduced_encoded.csv",
    index=False
)

print(df_reduced_encoded.shape)
df_reduced_encoded.head()

(958, 16)

,top_left_square_b,top_left_square_o,top_left_square_x,top_right_square_b,top_right_square_o,top_right_square_x,middle_middle_square_b,middle_middle_square_o,middle_middle_square_x,bottom_left_square_b,bottom_left_square_o,bottom_left_square_x,bottom_right_square_b,bottom_right_square_o,bottom_right_square_x,class
0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,1
1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,1
2,0,0,1,0,0,1,0,1,0,0,1,0,0,0,1,1
3,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1
4,0,0,1,0,0,1,0,1,0,1,0,0,1,0,0,1